amazonProperties:
   endpointUrl: https://s3.us-east-2.amazonaws.com 
   accessKey: AKIASB4WQETW6YE7ZE6Z
   secretKey: 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
   bucketName: acharyademo
spring:
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB